version: "3"

services:
  neo4j:
    build: ./neo4j
    container_name: "neo4j-social-network-analysis"
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    environment:
      # DB_HOST and DB_PORT values would appear in command-line output as:
      # heimdall-neo4j | 2021-01-26 21:51:22.234-0800 INFO  Remote interface available at http://localhost:7474/
      - DB_HOST=localhost
      - DB_PORT=7474

      # Make sure this matches the NEO4J_AUTH environment variable declared in ./neo4j/v4.x.x/Dockerfile
      - DB_USER=neo4j
      - DB_PASSWORD=password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true

      # Please set 'dbms.allow_upgrade' to 'true' in your configuration file and try again. Detailed description: Upgrade is required to migrate store to new major version.
      - NEO4J_dbms_allow__upgrade=true

      # Timezone - Default is UTC
      - NEO4J_dbms_db_timezone=SYSTEM
      - NEO4J_db_temporal_timezone=America/Los_Angeles
